language: python
python:
  - 3.9

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

script:
  - python -m unittest tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: master